# Sample stellar.toml

#   The endpoint which clients should query to resolve stellar addresses
#   for users on your domain.
FEDERATION_SERVER="https://stellarid.io/federation/"

# asset with meta info
[[CURRENCIES]]
code="Lugia"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Lugia"
desc="Is a Psychic/Flying Legendary Pokémon. Lugia is an immense, draconian and mythical Pokémon with avian qualities. It has silver-white feathers over most of its body, except for its blue underbelly. Lugia has ten fins running along its back, which stand upward while flying, but lie flat on its back in the water and on land.Known as the Guardian of the Seas, Lugia is tremendously intelligent and is very gentle with the life around it, despite its colossal size. Due to the fact that it can blow houses away with the single flap of its wings, it isolates itself deep within the great current, to prevent it from harming civilization. Lugia is also intelligent enough to even speak telepathically, like Mewtwo."
conditions="There will be only 1 Lugia in existence."
image="https://i.imgur.com/N2xY8xY.png"

[[CURRENCIES]]
code="Caterpie"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Caterpie"
desc="Caterpie is a worm-like Pokémon that is mainly green in color with a tan underside. Just below its head are four, tiny legs that are used only for movement. On top of its head is a red, 'y-shaped' antenna, which can be used to produce an odor used in self-defense, in case something tries to hurt it."
conditions="There will be only 9,789 Caterpies in existence."
image="https://i.imgur.com/BvuSEpD.png"

[[CURRENCIES]]
code="Diglett"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Diglett"
desc="Digletts are small, brown moles with two small eyes and a large pink/red nose. Since part of its body is underground, we don't know whether or not Diglett has feet, tail(s), etc. However, in Pokémon Mystery Dungeon Red Rescue Team and Blue Rescue Team, the rescued Diglett (after Skarmory kidnapped him) claimed to say his feet were getting cold (Which thereafter caused an awkward moment of silence)."
conditions="There will be only 11,021 Digletts in existence."
image="https://i.imgur.com/5tqacCJ.png"

[[CURRENCIES]]
code="Charmander"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Charmander"
desc="Charmander is a small, bipedal, dinosaur-like Pokémon. Most of its body is colored orange, while its underbelly is a pale light-yellow color. Charmander, like its evolved forms, has a flame that constantly burns on the end of its tail. However, If the flame on Charmander's tail goes out, Charmander is known to die."
conditions="There will be only 1,019 Charmanders in existence."
image="https://i.imgur.com/5nCIbl4.png"

[[CURRENCIES]]
code="Raticate"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Raticate"
desc="Compared to Rattata, Raticate is far more of a predator, and the majority of its features are adapted for this purpose. Its most notable feature are its large teeth; like most rodents, Raticate's teeth grow continuously throughout its life, and must be constantly worn down by gnawing. It is also known that Raticate's fangs are tough enough to break through concrete. It has long whiskers and a long tail. Raticate looks like a rat, just like Rattata. Raticate tends to stand on its hind legs, as opposed to its pre-evolution."
conditions="There will be only 19,199 Raticates in existence."
image="https://i.imgur.com/erz07Gc.png"

[[CURRENCIES]]
code="Cubone"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Cubone"
desc="Cubone, known as the Lonely Pokémon, appears to be a small, brown, dinosaur-like Pokémon that constantly wears its deceased mother's skull like a helmet. The skull masks its true face from view, which makes it a puzzlement for many Trainers and researchers. Its cries echo within the skull and it comes out as a pained and sad melody. On the night of a full moon, it cries, for it seems to recognize its mother's face in the moon. Its tears create stains on the skull. Cubone has a plump body with a paler-colored underbelly, with strong, clawed limbs to carry a bone as a weapon around wherever it goes. Cubone has a single, nailed toe on each foot, with two spikes on its back. A small tail is also present for balance, but it can be used for attacking." 
conditions="There will be only 119 Cubones in existence."
image="https://i.imgur.com/aXiVHmo.png"

[[CURRENCIES]]
code="Bellsprout"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Bellsprout"
desc="Bellsprout is a plant-like Pokémon. The body is a thin brown root and stem system. Bellsprout has two root-like legs. It has two leaves on each side. Its head is yellow and shaped like a bulb, the tip is colored pink, and it has the smallest amount of dirt on its feet."
conditions="There will be only 979,121 Bellsprouts in existence."  
image="https://i.imgur.com/5bvdi4R.png"

[[CURRENCIES]]
code="Eevee"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Eevee"
desc="Eevee (Japanese: イーブイ Iibui) is a Normal-type Pokémon introduced in Generation I. It's well-known for being the Pokémon with the highest number of evolution possibilities, due to its unstable genetic makeup. Eevee is a small, fennec fox-like creature with bushy, brown fur. Its muzzle is very cat-like, with a small, black, triangular nose. It has a fluffy cream-colored ruff around its neck and a short, bushy, fox-like tail with a creamy tip."
conditions="There will be only 10,171 Eevees in existence."
image="https://i.imgur.com/oqaDx5r.png"


[[CURRENCIES]]
code="Meowth"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Meowth"
desc="Meowth (Japanese: ニャース Nyasu) is a Normal-type Pokémon introduced in Generation I, and a Dark-type introduced in Generation VII. Meowth is a small, bipedal, feline Pokémon. It has two white whiskers on each side of its oval-shaped face and two hairs sticking up on either side of the coin-like gem on its forehead, and highly resembles a cat. Meowth's tail and feet are cream-colored like the rest of it, but they are brown at the end."
conditions="There will be only 3,629 Meowths in existence."
image="https://i.imgur.com/8XpBxXs.png"

[[CURRENCIES]]
code="Abra"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Abra"
desc="Abra (Japanese: ケーシー Keeshii) is a Psychic-type Pokémon introduced in Generation I. Abra is a golden-brown, human-like fox Pokémon with three fingers and toes on both arms and legs. Its eyes are mostly closed because of its tendency to sleep a lot. The shoulders are brown. Abra has a long tail with one brown stripe. Feet have 3 sharp claws, 2 on the front and 1 on the heel. It has slightly-pointed ears and its body looks slightly like it has a type of body armour on its top half."
conditions="There will be only 7,829 Abras in existence."
image="https://i.imgur.com/Mt6SxjU.png"

[[CURRENCIES]]
code="Squirtle"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Squirtle"
desc="Squirtle (ゼニガメ Zenigame) is a Water-type Pokémon introduced in Generation I. It evolves into Wartortle starting at level 16. It is one of the three Starter Pokémon that can be chosen in Kanto region. Squirtle is a small, light-blue Pokémon with an appearance similar to a turtle. With its aerodynamic shape and grooved surface, Squirtle's shell helps it wade through the water very quickly. It also offers protection in battle. Like turtles, Squirtle has a shell that covers its body with holes that allow its limbs, tail, and head to be exposed. Unlike a turtle, Squirtle is ordinarily bipedal."
conditions="There will be only 129,314 Squirtles in existence."
image="https://i.imgur.com/1ECCzFU.png"

[[CURRENCIES]]
code="Zubat"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Zubat"
desc="Zubat (Japanese: ズバット Zubatto) is a Poison/Flying-type Pokémon introduced in Generation I. Zubat resembles a blue bat. It has a short, round body, purple wings, and slim legs missing feet. Zubat has no eyes, so it uses sound waves (echolocation) to navigate, like a real bat does. A female Zubat has smaller teeth than those of a male's. Strangely, it can use the move Mean Look, despite not having any eyes."
conditions="There will be only 1,029,921 Zubats in existence."
image="https://i.imgur.com/zyODO5e.png"

[[CURRENCIES]]
code="Omanyte"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Omanyte"
desc="Omanyte (Japanese: オムナイト Omunaito) is a Rock/Water-type Fossil Pokémon introduced in Generation I that can be resurrected from a Helix Fossil. It is Kabuto's counterpart. Omanyte is a snail-like Pokémon that died out millions of years ago. Omanyte's sturdy shell protects it from enemy attacks. It has many tentacles, which it used to crawl along the muddy seafloor. It has two large eyes that just stick out under its curvy shell. It is based on the ancient sea-creatures Ammonites."
conditions="A limited edition given for free for the ones who add its trustline"
image="https://i.imgur.com/aSQIDHa.png"

[[CURRENCIES]]
code="Pidgeot"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Pidgeot"
desc="Pidgeot (Japanese: ピジョット Pijotto) is a Normal/Flying-type Pokémon introduced in Generation I. It is the evolved form of Pidgeotto, and the final evolution of Pidgey. Pidgeot resembles a large, feathery bird with huge wings. It has a brightly colored crest and tail. Many trainers are drawn to Pidgeot because of its lovely feathers. The beautiful colors of its crest are particularly striking. It is easily confused with Pidgeotto because the only difference without a relative size comparison is that Pigeot's tail and crest coloring switch from those of Pidgeotto's." 
conditions="There will be only 91,569 Pidgeots in existence."
image="https://i.imgur.com/UGtix3c.png"

[[CURRENCIES]]
code="Psyduck"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Psyduck"
desc="Psyduck (Japanese: コダック Kodakku) is a Water-type Pokémon introduced in Generation I. Psyduck can have either the ability Damp or Cloud Nine. Damp is an ability that will prevent the opponent from self destructing, while Cloud Nine prevents the effects of weather. It suffers from a constant headache. From time to time, it's headache causes it psychic abilities to increase tenfold."
conditions="There will be only 9,061 Psyducks in existence."
image="https://i.imgur.com/0qTpu2I.png"

[[CURRENCIES]]
code="Paras"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Paras"
desc="Paras (Japanese: パラス Paras) is a Bug/Grass-type Pokémon introduced in Generation I. Paras is very crablike, as it has six legs. The front two legs are very large, allowing Paras to grip on to prey and its environment."
conditions="There will be only 19,971,061 Paras in existence."
image="https://i.imgur.com/hxcIFqO.png"

[[CURRENCIES]]
code="Weedle"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Weedle"
desc="Weedle (Japanese: ビードル Biidoru) is a Bug/Poison-type Pokémon introduced in Generation I. Weedle has the ability Shield Dust, which will block any side effect caused by an opposing attack. With its great scent it can smell the leaves it likes best." 
conditions="There will be only 161,769 Weedles in existence."
image="https://i.imgur.com/JOefjtW.png"

[[CURRENCIES]]
code="Venonat"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Venonat"
desc="Venonat (Japanese: コンパン Konpan) is a Bug/Poison-type Pokémon introduced in Generation I. Venonat is covered in large, purple fur. The feet of Venonat are brown and are about half as long as Venonat itself with its hands being the same color but a third of the size. Venonat can have the ability Compoundeyes or the ability Tinted Lens. Compoundeyes increases Venonat's accuracy by 30%. Tinted Lens increases the power of not-very-effective moves by 1.5x. Venonat's eyes are very accurate: they enable Venonat to easily catch extremely small prey. Conway has one in the episode Camping It Up."
conditions="There will be only 8,859 Venonats in existence."
image="https://i.imgur.com/qtElRJB.png"

[[CURRENCIES]]
code="Slowpoke"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Slowpoke"
desc="Slowpoke (Japanese: ヤドン Yadon) is a Water/Psychic-type Pokémon introduced in Generation I. Slowpoke can have the abilities Oblivious or Own Tempo. Oblivious prevents Slowpoke from being infatuated. Own Tempo prevents Slowpoke from being confused. Although slow, Slowpoke is skilled at fishing with its tail, and it does not feel pain if its tail is bitten."
conditions="There will be only 19,569 Slowpokes in existence."
image="https://i.imgur.com/fu3iNgJ.png"

[[CURRENCIES]]
code="Cyndaquil"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Cyndaquil"
desc="Cyndaquil (Japanese: ヒノアラシ Hinoarashi) is the Fire-type Starter Pokémon of the Johto region. All Cyndaquil have the ability Blaze which will cause its Fire-type attacks to do 150% damage when its health is below 1/3 its max HP. Cyndaquil are generally timid and not naturally aggressive, and are often seen curled up into a ball for protection."
conditions="There will be only 3,033 Cyndaquils in existence."
image="https://i.imgur.com/rYVGnAN.png"

[[CURRENCIES]]
code="Vulpix"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Vulpix"
desc="Vulpix (Japanese: ロコン Rokon) is a Fire-type Pokémon introduced in Generation I, and an Ice-type introduced in Generation VII which is exclusive to Pokémon Sun. Vulpix are fox-like Pokémon with reddish-brown fur. Vulpix's most distinctive feature is its six orange tails that are curled at the tips. According to the Pokédex, when it is born, Vulpix possesses one snow white tail that eventually splits into many tails as it grows older. Vulpix are very intelligent. When they face a stronger enemy, they'll distract the enemy by feigning injury and then escape. According to the Pokédex, Vulpix have a flame inside their body that never goes out. This is presumably what gives it the ability to use fire attacks such as Flamethrower. "
conditions="There will be only 11,069 Vulpix in existence."
image="https://i.imgur.com/kCXrigU.png"

[[CURRENCIES]]
code="Bulbasaur"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Bulbasaur"
desc="Bulbasaur (フシギダネ Fushigidane) is a Grass/Poison-type Pokémon introduced in Generation I. It evolves into Ivysaur starting at level 16. It is one of the three Starter Pokémon that can be chosen in the Kanto region. Bulbasaur often rests in bright places so its bulb can absorb sunlight. It can be seen napping in bright sunlight. While it sleeps, the seed on its back catches the rays and uses the energy to grow."
conditions="There will be only 9,789 Bulbasaurs in existence."
image="https://i.imgur.com/goklpGE.png"

[[CURRENCIES]]
code="Articuno"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Articuno"
desc="Articuno (Japanese: フリーザー Furiizaa) is an Ice/Flying-type Legendary Pokémon introduced in Generation I. It is part of the Kanto Legendary Birds, along with Zapdos and Moltres. Articuno is a large bird with blue plumage. Its colouring is darkest on its head crest and long, streaming tail. Its body is coloured sky-blue, while growing lighter on its front, and its chest is a lighter blue than anything. Its most distinctive trait is its large wings, which are said to be made of ice. In terms of physical strength, Articuno is the strongest out of the three Legendary Birds; as shown in the Anime, Articuno is able to lift one of Team Rocket's mechas with its talons."
conditions="There will be only 3 Articunos in existence."
image="https://i.imgur.com/VUoHK9t.png"

[[CURRENCIES]]
code="Oddish"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Oddish"
desc="Oddish (Japanese: ナゾノクサ Nazonokusa) is a Grass/Poison-type Pokémon introduced in Generation I. Oddish is a nocturnal Pokémon, using moonlight rather than the sun's rays for photosynthesis. During the day, Oddish avoids the sun's heat and brightness by burying itself into the earth, leaving only the leaves on top of its head visible above ground. Oddish looks like a small animated plant. Its body is blue, with two small feet and red eyes. On top of its head grows a large clump of five long green leaves."
conditions="There will be only 39,589 Oddish in existence."
image="https://i.imgur.com/8acoinn.png"

[[CURRENCIES]]
code="Charmeleon"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Charmeleon"
desc="Charmeleon (リザード Rizaado) is a Fire-type Pokémon introduced in Generation I. Charmeleon is a small, bipedal, dinosaur-like Pokémon with an appearance similar to that of its pre-evolved form, Charmander. Charmeleon, like its other evolutionary forms, can naturally breathe fire. Its powers, though, are much greater than Charmander's, but not as great as Charizard's."
conditions="There will be only 101 Charmeleons in existence."
image="https://i.imgur.com/KG7T0wt.png"

[[CURRENCIES]]
code="Jigglypuff"
issuer="GDKDKVEYV4TSELBCMNFFR7FAX7CYY6LYOIOR5P2LMB2T5S4N2V5A5IW6"
display_decimals=2
name="Jigglypuff"
desc="Jigglypuff (Japanese: プリン Purin) is a Normal/Fairy-type Pokémon introduced in Generation I. Before Generation VI, it was a pure Normal-type. Jigglypuff is a balloon Pokémon. Its body is globular, pink, fluffy, cuddly and accented with stubby appendages, a tiny tuft of a single curl of hair and enormous, blue eyes, featuring green eyes for its Shiny version. Its skin is rubbery and stretchy."
conditions="There will be only 59,839 Jigglypuffs in existence."
image="https://i.imgur.com/uwe7mkr.png"



# optional extra information for humans
# Useful place for anchors to detail various policies and required info

###################################
# Required compliance fields:
#      name=<recipient name>
#      addr=<recipient address>
# Federation Format:
#        <phone number>*anchor.com
#        Forwarding supported by sending to: forward*anchor.com
#           forward_type=bank_account
#           swift=<swift code of receiving bank>
#           acct=<recipient account number at receiving bank>
# Minimum Amount Forward: $2 USD
# Maximum Amount Forward: $10000 USD
